### PR TITLE
Export solution pdf

### PR DESCRIPTION
**Pull request by joshbduncan**
Additional functionality in response to issues #14 and #15.

## Added
- You can now export the puzzle solution along with the puzzle using the `save()` method. Just specify `solution=True` after the path.
    - If you are exporting a PDF then a second page will be added with the puzzled words highlighted in red (just like the `show(solution=True)` method)
    - If you are exporting to CSV the puzzle solution will be included at the bottom of the csv below the answer key.

## Changed
- `save()` method now accepts the `solution` argument.
- -c, --cheat cli option now works with the -o, --output option to include the puzzle solution within the output file (csv or pdf)
- To clean things up a bit, `export_pdf_file()` and `export_csv_file()` now accept a WordSearch object as the main argument.

### CODE REVIEW

**Comment by ALEXDINO7** [comment]
Thanks for the update but still not working when i added    solution=True i get the bellow error

puzzle.save(path="./puzzle.pdf",solution=True)
TypeError: WordSearch.save() got an unexpected keyword argument 'solution'

**Comment by joshbduncan** [comment]
Yeah, I haven't merged the new feature code and released a new version yet... So if you installed it using pip you would get that error. I just wanted to get your feedback on the attached pdf to see if that is the result you were looking for before I released the new version.

**Comment by joshbduncan** [comment]
@ALEXDINO7 you can install the new program for testing on your system using the command below. This will install the latest code from the export-solution-pdf branch that is tied to this PR.

```bash
# if you are not using a virtual environment
pip install --user git+https://github.com/joshbduncan/word-search-generator.git@export-solution-pdf

# if you are using a virtual environment
pip install git+https://github.com/joshbduncan/word-search-generator.git@export-solution-pdf
```

**Comment by ALEXDINO7** [comment]
> @ALEXDINO7 you can install the new program for testing on your system using the command below. This will install the latest code from the export-solution-pdf branch that is tied to this PR.
> 
> ```shell
> # if you are not using a virtual environment
> pip install --user git+https://github.com/joshbduncan/word-search-generator.git@export-solution-pdf
> 
> # if you are using a virtual environment
> pip install git+https://github.com/joshbduncan/word-search-generator.git@export-solution-pdf
> ```

wooow it's working now you are the best

**Pull request merged**
